#!/usr/local/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use Minicli\Command\CommandCall;

$app = new App();

$app->setSignature('./minicli debug');

$app->registerCommand('debug', function(CommandCall $input) use($app) {
    $printer = $app->getPrinter();
    $printer->info("Minicli 2.0 Sandbox", true);
    $printer->info("System info: PHP " . PHP_VERSION . PHP_EXTRA_VERSION);
    $printer->success("Input info:");

    var_dump($input);

    $printer->display("Check https://docs.minicli.dev for documentation.");
});

$app->runCommand($argv);